node locally updates on args
Accern/accern-xyme pull request #44
Opened 2020-12-29 18:39 UTC by ys3244

2020-12-30 19:05 UTC, jckhang commented on accern_xyme/accern_xyme.py
> +    def get_node(self) -> 'NodeHandle':
remove

2020-12-30 19:05 UTC, jckhang commented on accern_xyme/accern_xyme.py
> +                node=self.get_node())
self

2020-12-30 19:08 UTC, jckhang requested changes
some change...node handle does not need get_node, just use self

2021-01-04 13:10 UTC, JosuaKrause approved these changes
lgtm

2021-03-18 19:05 UTC, JosuaKrause commented
solved by https://github.com/Accern/accern-xyme/pull/47

2021-03-18 19:05 UTC, closed without merging